service: hello-world

provider:
  name: aws
  runtime: go1.x
  region: us-west-2
  stage: dev
  deploymentBucket:
    name: org-name-us-west-2-serverless-deploys

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
    - http:
        path: hello
        method: post
  world:
    handler: bin/world
